import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';

// Sitemap is generated by src/pages/sitemap.xml.ts (manual — see Stage 5 notes).

// https://astro.build/config
export default defineConfig({
  site: 'https://sanisafe.ie',
  integrations: [tailwind()],
  build: {
    inlineStylesheets: 'auto',
  },
  compressHTML: true,
});
